### ISSUE TITLE
Finetune has error when using accelerate

### ISSUE THREAD

**Issue by zaidato** [SWivid/F5-TTS#135]
Thanks you for great works.
I am trying to finetune F5TTS_Base model with model_1200000.pt pretrained model. I followed your steps but i found that I cannot load pretrained model with "accelerate launch train.py" cmd, all layers of the model have shape: torch.Size([0]). It causes mismatch size between current model and pretrained model. 
But when I use "python train.py", it run correctly on single GPU.
Could you please help me with this problem? 
Thank you in advance!

**Comment by SWivid** [comment]
no clear idea for it, maybe check accelerate config first, see if it's all right
generally if `python train.py` works, `accelerate launch train.py` will work

**Comment by zaidato** [comment]
This is my default_config.yaml 
compute_environment: LOCAL_MACHINE
debug: true
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: false
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by SWivid** [comment]
not quite sure if FSDP works, we haven't tried it.
maybe just multi-gpu

**Comment by zaidato** [comment]
can you share with me your default_config.yaml?

**Comment by zaidato** [comment]
thank you for your help. FSDP causes the error

**Comment by ZhikangNiu** [comment]
I will close this issue. If you have other questions, you can reopen this issue.
BTW, here is my config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: true
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
