### ISSUE TITLE
TOML configuration file not reading ckpt_file and vocab_file variables

### ISSUE THREAD

**Issue by agarzon** [SWivid/F5-TTS#452]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

WSL Debian 12.

Using CLI inference only.

### Steps to Reproduce

1. Create a configuration file like in the example https://github.com/SWivid/F5-TTS/blob/main/src/f5_tts/infer/examples/basic/basic.toml

But add the additional variables **ckpt_file** and **vocab_file**

```toml
# F5-TTS | E2-TTS
model = "F5-TTS"
ckpt_file = "models/model_1200000.safetensors"
vocab_file = "models/vocab.txt"
ref_audio = "infer/examples/basic/basic_ref_en.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "Some call me nature, others call me mother nature."
gen_text = "I don't really care what you call me. I've been a silent spectator, watching species evolve, empires rise and fall. But always remember, I am mighty and enduring."
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"
```

2. Have of course the checkpoint and vocab.txt file in the correct path.

3. Execute the CLI and notice how its using models from default paths

```bash
f5-tts_infer-cli -c basic.toml
```

The script is using the models loaded from different path instead the ones assigned. However if you pass the same variables as arguments then it does work:

```bash
f5-tts_infer-cli -c basic.toml  -p models/model_1200000.safetensors -v models/vocab.txt
```

I did not tested yet but I believe the same will happen with **load_vocoder_from_local** and **vocoder_name**

### ✔️ Expected Behavior

The script should use the variables set in the TOML file

### ❌ Actual Behavior

The script is ignoring those variables in the TOML, but it works if passed as arguments via CLI
