### ISSUE TITLE
docker-compose on image swivid/f5-tts:main doesn't seem to be porting gradio to 7860

### ISSUE THREAD

**Issue by apensotti** [SWivid/F5-TTS#788]
### Checks

- [x] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [x] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [x] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [x] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Compose from docs

``` 
f5-tts:
    image: ghcr.io/swivid/f5-tts:main
    ports:
      - "7860:7860"
    environment:
      GRADIO_SERVER_PORT: 7860
    entrypoint: ["f5-tts_infer-gradio", "--port", "7860", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  f5-tts:
    driver: local
```
Container Output:
2025-02-15 11:31:06 Building prefix dict from the default dictionary ...
2025-02-15 11:31:07 Dumping model to file cache /tmp/jieba.cache
2025-02-15 11:31:07 Loading model cost 0.353 seconds.
2025-02-15 11:31:07 Prefix dict has been built successfully.

Running 
Ubuntu-24.04
Nvidia 40xx

### Steps to Reproduce

1. Create docker-compose.yml file from docs
2. run `docker-compose up --build`

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/d34537e9-dbf0-478e-ba47-dadf3c507948" />

4. run `http://localhost:7860`
5. Response below
<img width="625" alt="Image" src="https://github.com/user-attachments/assets/3169c64b-f8d4-4280-bdd0-2634fafa88dc" />

<img width="526" alt="Image" src="https://github.com/user-attachments/assets/be1836d9-af48-49d4-84eb-6504c1c5f927" />

### ✔️ Expected Behavior

Expected to see a gradio page

### ❌ Actual Behavior

Get `local host didn't send any data`
