### ISSUE TITLE
How to release video memory without ending the program when deploying F5-TTS using Docker to achieve switching and using between multiple AI applications

### ISSUE THREAD

**Issue by axh-xecoy** [SWivid/F5-TTS#899]
### Checks

- [ ] This template is only for usage issues encountered.
- [x] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [x] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [x] I am using English to submit this issue to facilitate community communication.

### Environment Details

``` yml
x-proxy-env: &proxy-env
  http_proxy: http://192.168.0.100:7890
  https_proxy: http://192.168.0.100:7890
  no_proxy: "localhost,127.0.0.1,.internal"

services:
  f5-tts:
    image: ghcr.io/swivid/f5-tts:main
    container_name: f5-tts
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]  # 请求 GPU 资源
    environment:
      <<: *proxy-env
    ports:
      - "7860:7860"
    volumes:
      - f5-tts:/root/.cache/huggingface/hub/
      - ./ckpts:/workspace/F5-TTS/ckpts
    command: f5-tts_infer-gradio --host 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  f5-tts:
```

### Steps to Reproduce

 I deployed F5-TTS in the way of Docker. There is a problem. There are multiple AI applications on my Linux server, but the video memory size of the server does not support these applications to run simultaneously. I want to know how I can release the video memory without ending the program so that I can switch and use between multiple AI applications. If I have to restart it every time after using it to release the video memory, this method is too troublesome.
